### DISCUSSION TITLE
build requirement gets removed for no apparent reason

### DISCUSSION THREAD

**Discussion by Dobatymo** [tox-dev/toml-fmt#10] [General]
Hi, great project!

I have the following in my pyproject file

```toml
[build-system]
requires = [
  "cython==3.0.11",
  "numpy==1.22.2; python_version<'3.9'",
  "numpy>=2; python_version>='3.9'",
  "setuptools",
]
```
when running `pyproject-fmt==2.2.4` using pre-commit the ` "numpy==1.22.2; python_version<'3.9'",` line gets removed. Is that a bug or some configuration option I missed?
