### ISSUE TITLE
misparsed `requires-python="~=3.12.7"`

### ISSUE THREAD

**Issue by graingert-coef** [tox-dev/toml-fmt#20]
input:

```toml
[build-system]
build-backend = "flit_core.buildapi"

requires = [ "flit-core>=3.2,<4" ]

[project]
name = "demo-requires-python"
license = { file = "LICENSE" }
authors = [ { name = "Thomas Grainger", email = "tagrain@gmail.com" } ]
requires-python = "~=3.12.7"
classifiers = [
  "License :: OSI Approved :: MIT License",
]
dynamic = [ "description", "version" ]
```

output:

```toml
[build-system]
build-backend = "flit_core.buildapi"

requires = [ "flit-core>=3.2,<4" ]

[project]
name = "demo-requires-python"
license = { file = "LICENSE" }
authors = [ { name = "Thomas Grainger", email = "tagrain@gmail.com" } ]
requires-python = "~=3.12.7"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dynamic = [ "description", "version" ]
```

expected output:

```toml
[build-system]
build-backend = "flit_core.buildapi"

requires = [ "flit-core>=3.2,<4" ]

[project]
name = "demo-requires-python"
license = { file = "LICENSE" }
authors = [ { name = "Thomas Grainger", email = "tagrain@gmail.com" } ]
requires-python = "~=3.12.7"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
]
dynamic = [ "description", "version" ]
```
