### ISSUE TITLE
Creates invalid syntax in the presence of raw strings

### ISSUE THREAD

**Issue by flying-sheep** [tox-dev/toml-fmt#22]
For me, it changed the valid TOML

```toml
[tool.ruff]
lint.flake8-copyright.notice-rgx = 'SPDX-License-Identifier: MPL-2\.0'
```

into the invalid `…MPL-2\.0"` (`\.` is not a valid escape sequence in a `""`-string)

`pyproject-fmt` needs to preserve raw strings everywhere.
