### ISSUE TITLE
It should not remove trove entries declaring support for unreleased python version

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/toml-fmt#61]
Current default behavior of removing 3.14 or newer from trove support is detrimental to projects that are already testing with python 3.14 even before its release.

I think that this feature should not be enabled by default because it prevents users from enabling support for unreleased python versions before they reach GA. This slows down the entire ecosystem and delays adopting new versions for everyone.

I know that in theory I should be able to use `--max-supported-python=3.14` to prevent its removal but to my surprise when I tried to use the pre-commit hook like below it did not work:

```
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
      - id: pyproject-fmt
        args: ["--max-supported-python=3.99"]
```

Something preventing me to disable this feature.
