### ISSUE TITLE
Space is added on reordering

### ISSUE THREAD

**Issue by henryiii** [tox-dev/toml-fmt#7]
When two lines are reordered, a space is sometimes added:

Before:

```toml
[build-system]
requires = [
  "hatchling",
]
build-backend = "hatchling.build"

[project]
```

After:

```toml
[build-system]
build-backend = "hatchling.build"

requires = [
  "hatchling",
]

[project]
```
